services:
  - type: web
    name: aditi-portfolio-backend
    env: python
    buildCommand: pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app
    envVars:
      - key: TOGETHER_API
        sync: false
    healthCheckPath: /health
