services:
  - type: web
    name: aditi-portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: TOGETHER_API
        sync: false
    healthCheckPath: /health
